### ISSUE TITLE
Bad results during inference

### ISSUE THREAD

**Issue by hhllxx1121** [NExT-GPT/NExT-GPT#35]
I used the 7b_tiva_v0 weights downloaded from Huggingface, and when I run `bash script/app.sh`, I got the following results.
![image](https://github.com/NExT-GPT/NExT-GPT/assets/96508996/e2367b88-aaec-4c73-9b52-a55ce0bfab0b)

**Comment by NomanTrips** [comment]
@hhllxx1121 I encountered the same error when trying to generate images or video with the demo. To fix, I added this line to demo_app.py right below where the parser arguments are added:

parser.add_argument('--mode', type=str, default='validate')

I didn't test this with video generation because I'm getting cuda oom running on my 3090. The image generation worked though.

**Comment by hhllxx1121** [comment]
> @hhllxx1121 I encountered the same error when trying to generate images or video with the demo. To fix, I added this line to demo_app.py right below where the parser arguments are added:
> 
> parser.add_argument('--mode', type=str, default='validate')
> 
> I didn't test this with video generation because I'm getting cuda oom running on my 3090. The image generation worked though.

Thank you very much, you are right, I tried generating a video and it was okay too
