### ISSUE TITLE
Regarding commercial use

### ISSUE THREAD

**Issue by abhimanyu891998** [NExT-GPT/NExT-GPT#9]
Hi, I see that you have used imageBind as the underlying model to generate embeddings, and your license is open for commercial use. However, as far as I know, imageBind is open for non-commercial usage only. Am not an expert at the licenses, but just wanted to know if I want to build a product on top of NExT-GPT (intended for commercial purposes), would it be an issue?

**Comment by scofield7419** [comment]
Hi @abhimanyu891998 thx for your interest.
We highlighted at the end of the readme, non-commercial use of the project. Because some of our backbone modules, e.g., ImageBind, SD, have the non-commercial terms; and other concerns of NExT-GPT for AIGC.
So sorry to say, it might be not allowed to build a commercial system with NExT-GPT, at least before you obtain permission from ImageBind, etc.
